"""Fix Summary model

Revision ID: d17bf0b1846c
Revises: 7ef4c174d24c
Create Date: 2025-12-06 12:27:38.494644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17bf0b1846c'
down_revision: Union[str, Sequence[str], None] = '7ef4c174d24c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('summaries', sa.Column('file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'summaries', 'files', ['file_id'], ['id'])
    op.drop_column('summaries', 'is_consolidated')
    op.drop_column('summaries', 'file_ids')
    op.drop_column('summaries', 'summary_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('summaries', sa.Column('file_ids', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('summaries', sa.Column('is_consolidated', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'summaries', type_='foreignkey')
    op.drop_column('summaries', 'file_id')
    op.drop_column('summaries', 'content')
    # ### end Alembic commands ###
