"""Fix Summary model 3

Revision ID: daa8ab7a5ccb
Revises: a7f2e8f07b7d
Create Date: 2025-12-06 14:16:25.993735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa8ab7a5ccb'
down_revision: Union[str, Sequence[str], None] = 'a7f2e8f07b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('summary_text', sa.Text(), nullable=True))
    op.add_column('summaries', sa.Column('file_ids', sa.String(), nullable=True))
    op.add_column('summaries', sa.Column('is_consolidated', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('summaries_file_id_fkey'), 'summaries', type_='foreignkey')
    op.drop_column('summaries', 'content')
    op.drop_column('summaries', 'file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('summaries', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('summaries_file_id_fkey'), 'summaries', 'files', ['file_id'], ['id'])
    op.drop_column('summaries', 'is_consolidated')
    op.drop_column('summaries', 'file_ids')
    op.drop_column('summaries', 'summary_text')
    # ### end Alembic commands ###
